// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "../interfaces/IZKVerifier.sol";
import "@openzeppelin/contracts/access/AccessControl.sol";

/// @title Groth16Verifier — On-chain ZK-SNARK verification for MCC state proofs
/// @notice Verifies Groth16 proofs using Ethereum's bn128 precompiled contracts.
///         Each connected chain has its own verification key (VK) registered by governance.
/// @dev    Uses EIP-196 (bn128 add/mul) and EIP-197 (bn128 pairing) precompiles.
///
///         Groth16 verification equation:
///           e(A, B) == e(alpha, beta) * e(sum_of_inputs, gamma) * e(C, delta)
///
///         Public inputs for MCC state proofs:
///           input[0] = chainId
///           input[1] = blockHeight
///           input[2] = uint256(stateRoot)  (bytes32 → uint256)
///
///         Proof format (256 bytes):
///           [0:64]   = A (G1 point: x, y)
///           [64:192] = B (G2 point: x1, x2, y1, y2)
///           [192:256] = C (G1 point: x, y)

contract Groth16Verifier is IZKVerifier, AccessControl {

    // ═══════════════════════════════════════════════════════════════
    //  CONSTANTS
    // ═══════════════════════════════════════════════════════════════

    /// @dev BN128 curve order
    uint256 internal constant PRIME_Q =
        21888242871839275222246405745257275088696311157297823662689037894645226208583;

    uint256 internal constant PROOF_SIZE = 256; // 8 × 32 bytes
    uint256 internal constant NUM_PUBLIC_INPUTS = 3;

    // ═══════════════════════════════════════════════════════════════
    //  TYPES
    // ═══════════════════════════════════════════════════════════════

    /// @notice Groth16 verification key for a specific chain
    struct VerificationKey {
        uint256[2]  alpha;      // G1 point
        uint256[2][2] beta;     // G2 point
        uint256[2][2] gamma;    // G2 point
        uint256[2][2] delta;    // G2 point
        uint256[2][] ic;        // Input commitments (NUM_INPUTS + 1 G1 points)
        bool exists;
    }

    // ═══════════════════════════════════════════════════════════════
    //  STATE
    // ═══════════════════════════════════════════════════════════════

    /// @notice Verification keys per chain
    mapping(uint64 => VerificationKey) internal _vks;

    /// @notice Registered chain count
    uint256 public vkCount;

    // ═══════════════════════════════════════════════════════════════
    //  EVENTS
    // ═══════════════════════════════════════════════════════════════

    event VerificationKeySet(uint64 indexed chainId);
    event VerificationKeyRemoved(uint64 indexed chainId);

    // ═══════════════════════════════════════════════════════════════
    //  ERRORS
    // ═══════════════════════════════════════════════════════════════

    error InvalidProofSize(uint256 size);
    error NoVerificationKey(uint64 chainId);
    error InvalidICLength(uint256 provided, uint256 expected);
    error ProofElementOutOfRange();
    error InputOutOfRange();
    error PairingFailed();

    // ═══════════════════════════════════════════════════════════════
    //  CONSTRUCTOR
    // ═══════════════════════════════════════════════════════════════

    constructor(address admin) {
        _grantRole(DEFAULT_ADMIN_ROLE, admin);
    }

    // ═══════════════════════════════════════════════════════════════
    //  VERIFICATION KEY MANAGEMENT
    // ═══════════════════════════════════════════════════════════════

    /// @notice Register a verification key for a chain
    /// @dev    VK is generated by the trusted setup ceremony for each chain's
    ///         state proof circuit. The IC array must have NUM_PUBLIC_INPUTS + 1
    ///         elements (one constant + one per public input).
    function setVerificationKey(
        uint64 chainId,
        uint256[2] calldata alpha,
        uint256[2][2] calldata beta,
        uint256[2][2] calldata gamma,
        uint256[2][2] calldata delta,
        uint256[2][] calldata ic
    ) external onlyRole(DEFAULT_ADMIN_ROLE) {
        if (ic.length != NUM_PUBLIC_INPUTS + 1) {
            revert InvalidICLength(ic.length, NUM_PUBLIC_INPUTS + 1);
        }

        VerificationKey storage vk = _vks[chainId];
        if (!vk.exists) vkCount++;

        vk.alpha = alpha;
        vk.beta = beta;
        vk.gamma = gamma;
        vk.delta = delta;
        vk.exists = true;

        // Clear and re-set IC array
        delete vk.ic;
        for (uint256 i = 0; i < ic.length;) {
            vk.ic.push(ic[i]);
            unchecked { ++i; }
        }

        emit VerificationKeySet(chainId);
    }

    /// @notice Remove a verification key
    function removeVerificationKey(uint64 chainId)
        external
        onlyRole(DEFAULT_ADMIN_ROLE)
    {
        if (!_vks[chainId].exists) revert NoVerificationKey(chainId);
        delete _vks[chainId];
        vkCount--;
        emit VerificationKeyRemoved(chainId);
    }

    /// @inheritdoc IZKVerifier
    function hasVerificationKey(uint64 chainId) external view returns (bool) {
        return _vks[chainId].exists;
    }

    // ═══════════════════════════════════════════════════════════════
    //  PROOF VERIFICATION
    // ═══════════════════════════════════════════════════════════════

    /// @inheritdoc IZKVerifier
    function verifyProof(
        uint64  chainId,
        uint64  blockHeight,
        bytes32 stateRoot,
        bytes   calldata proof
    ) external view returns (bool valid) {
        if (proof.length != PROOF_SIZE) revert InvalidProofSize(proof.length);
        if (!_vks[chainId].exists) revert NoVerificationKey(chainId);

        // Decode proof points
        uint256[8] memory p = abi.decode(proof, (uint256[8]));

        // Validate proof elements are on the curve (< PRIME_Q)
        for (uint256 i = 0; i < 8;) {
            if (p[i] >= PRIME_Q) revert ProofElementOutOfRange();
            unchecked { ++i; }
        }

        // Build public inputs
        uint256[NUM_PUBLIC_INPUTS] memory inputs;
        inputs[0] = uint256(chainId);
        inputs[1] = uint256(blockHeight);
        inputs[2] = uint256(stateRoot);

        // Validate inputs are in the field
        for (uint256 i = 0; i < NUM_PUBLIC_INPUTS;) {
            if (inputs[i] >= PRIME_Q) revert InputOutOfRange();
            unchecked { ++i; }
        }

        return _verifyGroth16(p, inputs, _vks[chainId]);
    }

    // ═══════════════════════════════════════════════════════════════
    //  INTERNAL — Groth16 Math
    // ═══════════════════════════════════════════════════════════════

    /// @dev Core Groth16 verification:
    ///      e(A, B) == e(alpha, beta) * e(vk_x, gamma) * e(C, delta)
    ///
    ///      Where vk_x = IC[0] + input[0]*IC[1] + input[1]*IC[2] + input[2]*IC[3]
    function _verifyGroth16(
        uint256[8] memory proof,
        uint256[NUM_PUBLIC_INPUTS] memory inputs,
        VerificationKey storage vk
    ) internal view returns (bool) {
        // Compute vk_x = IC[0] + sum(input[i] * IC[i+1])
        uint256[2] memory vk_x = [vk.ic[0][0], vk.ic[0][1]];

        for (uint256 i = 0; i < NUM_PUBLIC_INPUTS;) {
            uint256[2] memory product = _ecMul(vk.ic[i + 1], inputs[i]);
            vk_x = _ecAdd(vk_x, product);
            unchecked { ++i; }
        }

        // Negate A: -A = (A.x, PRIME_Q - A.y)
        uint256 negAy = proof[1] == 0 ? 0 : PRIME_Q - proof[1];

        // Build pairing input directly in memory (4 pairs × 6 uint256 = 24 words)
        // Each pair: G1.x, G1.y, G2.x_im, G2.x_re, G2.y_im, G2.y_re
        uint256[24] memory pairingInput;

        // Pair 1: (-A, B)
        pairingInput[0]  = proof[0];
        pairingInput[1]  = negAy;
        pairingInput[2]  = proof[3];  // B.x_im
        pairingInput[3]  = proof[2];  // B.x_re
        pairingInput[4]  = proof[5];  // B.y_im
        pairingInput[5]  = proof[4];  // B.y_re

        // Pair 2: (alpha, beta)
        pairingInput[6]  = vk.alpha[0];
        pairingInput[7]  = vk.alpha[1];
        pairingInput[8]  = vk.beta[0][1];
        pairingInput[9]  = vk.beta[0][0];
        pairingInput[10] = vk.beta[1][1];
        pairingInput[11] = vk.beta[1][0];

        // Pair 3: (vk_x, gamma)
        pairingInput[12] = vk_x[0];
        pairingInput[13] = vk_x[1];
        pairingInput[14] = vk.gamma[0][1];
        pairingInput[15] = vk.gamma[0][0];
        pairingInput[16] = vk.gamma[1][1];
        pairingInput[17] = vk.gamma[1][0];

        // Pair 4: (C, delta)
        pairingInput[18] = proof[6];
        pairingInput[19] = proof[7];
        pairingInput[20] = vk.delta[0][1];
        pairingInput[21] = vk.delta[0][0];
        pairingInput[22] = vk.delta[1][1];
        pairingInput[23] = vk.delta[1][0];

        // Call bn128 pairing precompile (address 0x08)
        uint256[1] memory result;
        bool success;
        assembly {
            success := staticcall(gas(), 0x08, pairingInput, 768, result, 32)
        }
        if (!success) revert PairingFailed();
        return result[0] == 1;
    }

    /// @dev EC point addition using precompile at address 0x06
    function _ecAdd(uint256[2] memory p1, uint256[2] memory p2)
        internal
        view
        returns (uint256[2] memory result)
    {
        uint256[4] memory input;
        input[0] = p1[0]; input[1] = p1[1];
        input[2] = p2[0]; input[3] = p2[1];

        bool success;
        assembly {
            success := staticcall(gas(), 0x06, input, 128, result, 64)
        }
        require(success, "ecAdd failed");
    }

    /// @dev EC scalar multiplication using precompile at address 0x07
    function _ecMul(uint256[2] memory p, uint256 scalar)
        internal
        view
        returns (uint256[2] memory result)
    {
        uint256[3] memory input;
        input[0] = p[0]; input[1] = p[1]; input[2] = scalar;

        bool success;
        assembly {
            success := staticcall(gas(), 0x07, input, 96, result, 64)
        }
        require(success, "ecMul failed");
    }

}
